# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MobileAxxessAssignment' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
 
  # Pods for MobileAxxessAssignment
  pod 'Alamofire'
  pod 'SnapKit', '~> 5.0.0'
  pod 'SDWebImage'


  target 'MobileAxxessAssignmentTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MobileAxxessAssignmentUITests' do
    # Pods for testing
  end

end
